DEFAULT_PAGE_SIZE = 12
DEFAULT_PAGE_NUMBER = 1
SKILLS_SEARCH_LIMIT = 10

PROJECT_NAME_MAX_LENGTH = 200
SKILL_NAME_MAX_LENGTH = 64
PROJECT_STATUS_MAX_LENGTH = 10

USER_NAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256
